### PR TITLE
support for ingesting messages using the archive api

### PR DESCRIPTION
**Pull request by czue**
probably easiest reviewed by commit, everything but the last commit is prework to actually make the change.

@nicpottier I noticed that I'm getting different results when importing messages from archives versus directly using the message API. Do you have any immediate reaction to why that would be? It's a bit hard to stitch together the exact behavior but two observations:

1. The archives seem to import more unique messages that aren't imported in any of the folders I'm currently checking ('inbox', 'flows', 'archived', 'outbox', 'incoming', 'sent') in the regular API
2. Sometimes, the non-archives seem to import multiple copies of the same message - whereas the archives don't.

### CODE REVIEW

**Comment by nicpottier** [comment]
Would need more specifics to help you track that down, but off the top of my head I would expect duplicates for things like sent/outbox for example depending on when you poll. Would be curious to see an exact example of where an archive contains a message not contained in other endpoints, that doesn't sound right off the top of my head but perhaps I'm not thinking of a case.

**Comment by czue** [comment]
thanks @nicpottier . I just shared a google sheet with you with some data in it. It looks like one difference is that the archives contain messages with `visibility="archived"` whereas those don't seem to appear in the main APIs. I haven't yet determined if there's any other discrepancies or validated your theory about the duplicates in the normal API

**Comment by nicpottier** [comment]
I think those would appear if you hit the API with the folder "archived" though? The API is slightly goofy in what / how it makes messages available since the indexes are huge there and tuned to what the UI presents, so ya there isn't exactly a 1-1 analog between it and the archives for messages. (the archives are a bit simpler in that ya, they are just everything)

**Comment by czue** [comment]
I am checking that folder though perhaps that's the root cause of the bug. When I hit https://app.rapidpro.io/api/v2/messages.json?folder=archived I get an empty result set (for the same organization in the sheet)

**Comment by nicpottier** [comment]
Heh, so I looked at one of those specifically (message 523231069) and it looks like that was actually manually deleted by a user after the archive was made. That's an artifact of us currently not yet deleting messages post archive (and therefore giving the opportunity for this kind of race) but that's what is happening there.

Looks like the other diffs are around the archives not having `modified_on`, which isn't a documented field on the messages endpoint but after internally chatting about it we are going to add. That's going to make us rebuild all the archives however so expect some odd archive API returns while that happens over the next few days.

**Comment by czue** [comment]
awesome, thanks for the help @nicpottier . is there any way for me to track the status of the archive rebuilds for a particular org?

**Comment by nicpottier** [comment]
All previous message archives were removed, so any message archives you see now should have `modified_on` in them. They should all be rebuilt in a day or so.

**Pull request merged**
