### PR TITLE
Py3 tweaks

### PR DESCRIPTION
**Pull request by czue**
@domdinicola some issues I ran to running (and troubleshooting) ingestion on py3

### CODE REVIEW

**Comment by domdinicola** [comment]
shall we merge this in the feature/python3 branch?

**Comment by czue** [comment]
this works on both 2 and 3 so i think can be merged as-is? i think it will be better to have a build that supports both before removing support for python2 to ease the transition process, no?

**Comment by domdinicola** [comment]
the __subclasses__ should work also on python 3 what's the issue with that?

**Comment by czue** [comment]
it was actually dependent on the order (which in python2 was always the order they were defined in `models.py` but in py3 seems nondeterministic)

**Comment by domdinicola** [comment]
can you check with Python3.7? if not we can merge!

**Comment by czue** [comment]
the py3.7 build passed so I'm happy with that

**Pull request merged**
