### PR TITLE
update rapirpro client

### PR DESCRIPTION
**Pull request by domdinicola**

### CODE REVIEW

**Comment by domdinicola** [comment]
@czue yes I tried the ingestion!
btw I cannot find the command fetch_all mentioned in the documentation

**Comment by czue** [comment]
thanks - can you also confirm re: the test file changes?

`fetch_all` was deleted (i think that was the mongo version). I'll update the docs soon.

**Comment by domdinicola** [comment]
@czue what do you mean with "the test file changes"?
I tested the ingestion and fixed the tests updating the json files from rapidpro repo

**Comment by czue** [comment]
(offlined)

**Pull request merged**
